volumes:
  node_modules:
  npm_cache:
  env_config:
  build_artifacts:
  app_logs:

services:
  dev:
    build:
      context: .
      dockerfile: docker/dev/Dockerfile/Dockerfile
    #ports:
    #  - "3000:3000"
    #  - "9229:9229"
    volumes:
      - ./src:/app/src
      - node_modules:/app/node_modules
      - npm_cache:/tmp/.npm-cache
      - env_config:/app/env
      - app_logs:/app/logs
    env_file:
      - ./env/dev.env
    container_name: dev-arg
    networks:
      - red-nginx
    #expose:
    #  - "3000"   
    restart: unless-stopped
    

  prod:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile/Dockerfile
    #ports:
    #  - "4000:4000"
    volumes:      
      - env_config:/app/env
    env_file:
      - ./env/prod.env
    container_name: pro-arg
    networks:
      - red-nginx
    expose:
      - "3000" 
    restart: unless-stopped
    

networks:
#  nginx:
#    driver: bridge
  red-nginx:
    external: true
    